var DATA = {
    playlists: {
        'test': {
            name: 'A playlist I made earlier',
            tracks: [
                new MODELS.Track('Infinity Milk', 'Dananananaykroyd'),
                new MODELS.Track('The Hell Song', 'Sum 41'),
                new MODELS.Track('Dry The Rain', 'The Beta Band'),
                new MODELS.Track('Woozy with Cider', 'James Yorkston'),
                new MODELS.Track('Yoshimi Battles the Pink Robots Pt. 1', 'The Flaming Lips'),
                new MODELS.Track('Stay Loose', 'Belle and Sebastian'),
                new MODELS.Track('Such Great Heights', 'The Postal Service'),
                new MODELS.Track('Stockholm Syndrome', 'Muse'),
                new MODELS.Track('New Slang', 'The Shins'),
                new MODELS.Track('Bluebird', 'Devendra Banhart'),
                new MODELS.Track('Von', 'Sigur Rós'),
                new MODELS.Track('Time Is The Enemy', 'Quantic'),
                new MODELS.Track('Get Ready for Love', 'Nick Cave & The Bad Seeds'),
                new MODELS.Track('Country House', 'Blur'),
                new MODELS.Track('Up In Arms', 'Foo Fighters')
            ]
        },
        'bevan': {
            name: 'Ben and Evan',
            tracks: [
                new MODELS.Track("Rockin' Stroll", "The Lemonheads"),
                new MODELS.Track("Confetti", "The Lemonheads"),
                new MODELS.Track("It's A Shame About Ray", "The Lemonheads"),
                new MODELS.Track("Rudderless", "The Lemonheads"),
                new MODELS.Track("My Drug Buddy", "The Lemonheads"),
                new MODELS.Track("The Turnpike Down", "The Lemonheads"),
                new MODELS.Track("Bit Part", "The Lemonheads"),
                new MODELS.Track("Alison's Starting To Happen", "The Lemonheads"),
                new MODELS.Track("Hannah & Gabi", "The Lemonheads"),
                new MODELS.Track("Kitchen", "The Lemonheads"),
                new MODELS.Track("Ceiling Fan In My Spoon", "The Lemonheads"),
                new MODELS.Track("Frank Mills", "The Lemonheads"),
                new MODELS.Track("Mrs. Robinson", "The Lemonheads"),
                new MODELS.Track("Shaky Ground", "The Lemonheads"),
                new MODELS.Track("It's A Shame About Ray (Demo)", "The Lemonheads"),
                new MODELS.Track("Rockin' Stroll (Demo)", "The Lemonheads"),
                new MODELS.Track("My Drug Buddy (Demo)", "The Lemonheads"),
                new MODELS.Track("Hannah & Gabbi (Demo)", "The Lemonheads"),
                new MODELS.Track("Kitchen (Demo)", "The Lemonheads"),
                new MODELS.Track("Bit Part (Demo)", "The Lemonheads"),
                new MODELS.Track("Rudderless (Demo)", "The Lemonheads"),
                new MODELS.Track("Ceiling Fan In My Spoon (Demo)", "The Lemonheads"),
                new MODELS.Track("Confetti (Demo)", "The Lemonheads"),
                new MODELS.Track("Hiroshima (B B B Benny Hit His Head)", "Ben Folds"),
                new MODELS.Track("Dr. Yang", "Ben Folds"),
                new MODELS.Track("The Frown Song", "Ben Folds"),
                new MODELS.Track("You Don't Know Me (feat. Regina Spektor)", "Ben Folds"),
                new MODELS.Track("Before Cologne", "Ben Folds"),
                new MODELS.Track("Cologne", "Ben Folds"),
                new MODELS.Track("Errant Dog", "Ben Folds"),
                new MODELS.Track("Free Coffee", "Ben Folds"),
                new MODELS.Track("Bitch Went Nuts", "Ben Folds"),
                new MODELS.Track("Brainwascht", "Ben Folds"),
                new MODELS.Track("Effington", "Ben Folds"),
                new MODELS.Track("Kylie From Connecticut", "Ben Folds"),
                new MODELS.Track("Brainwashed", "Ben Folds"),
                new MODELS.Track("Way to Normal", "Ben Folds"),
                new MODELS.Track("Lovesick Diagnostician", "Ben Folds"),
                new MODELS.Track("Free Coffee Town", "Ben Folds"),
                new MODELS.Track("Bitch Went Nutz", "Ben Folds"),
                new MODELS.Track("Frowne Song (Feeble Anthem)", "Ben Folds"),
                new MODELS.Track("Cologne (Piano Orchestra Version)", "Ben Folds"),
                new MODELS.Track("Hiroshima (B B B Benny Hit His Head)", "Ben Folds"),
                new MODELS.Track("You Don't Know Me (feat. Regina Spektor)", "Ben Folds"),
            ]
        },
        'toprock': {
            name: 'Top Tracks tagged with "metal"',
            tracks: [
                new MODELS.Track("Nothing Else Matters", "Metallica"),
                new MODELS.Track("Enter Sandman", "Metallica"),
                new MODELS.Track("Master of Puppets", "Metallica"),
                new MODELS.Track("One", "Metallica"),
                new MODELS.Track("Toxicity", "System of a Down"),
                new MODELS.Track("The Unforgiven", "Metallica"),
                new MODELS.Track("Chop Suey", "System of a Down"),
                new MODELS.Track("Fade to Black", "Metallica"),
                new MODELS.Track("Paranoid", "Black Sabbath"),
                new MODELS.Track("Run to the Hills", "Iron Maiden"),
                new MODELS.Track("Sad but True", "Metallica"),
                new MODELS.Track("The Number of the Beast", "Iron Maiden"),
                new MODELS.Track("Battery", "Metallica"),
                new MODELS.Track("Lonely Day", "System of a Down"),
                new MODELS.Track("Down With the Sickness", "Disturbed"),
                new MODELS.Track("Before I Forget", "Slipknot"),
                new MODELS.Track("Aerials", "System of a Down"),
                new MODELS.Track("Ace of Spades", "Motörhead"),
                new MODELS.Track("Du hast", "Rammstein"),
                new MODELS.Track("Cowboys From Hell", "Pantera"),
                new MODELS.Track("For Whom the Bell Tolls", "Metallica"),
                new MODELS.Track("Whiskey in the Jar", "Metallica"),
                new MODELS.Track("Iron Man", "Black Sabbath"),
                new MODELS.Track("The Trooper", "Iron Maiden"),
                new MODELS.Track("Fear of the Dark", "Iron Maiden"),
                new MODELS.Track("The Unforgiven II", "Metallica"),
                new MODELS.Track("Dragula", "Rob Zombie"),
                new MODELS.Track("Walk", "Pantera"),
                new MODELS.Track("Chop Suey!", "System of a Down"),
                new MODELS.Track("Killing in the Name", "Rage Against the Machine"),
                new MODELS.Track("Freak on a Leash", "KoЯn"),
                new MODELS.Track("Wait and Bleed", "Slipknot"),
                new MODELS.Track("Wherever I May Roam", "Metallica"),
                new MODELS.Track("Tears Don't Fall", "Bullet For My Valentine"),
                new MODELS.Track("2 Minutes to Midnight", "Iron Maiden"),
                new MODELS.Track("Symphony of Destruction", "Megadeth"),
                new MODELS.Track("Duality", "Slipknot"),
                new MODELS.Track("ATWA", "System of a Down"),
                new MODELS.Track("Fuel", "Metallica"),
                new MODELS.Track("Wish I Had an Angel", "Nightwish"),
                new MODELS.Track("Raining Blood", "Slayer"),
                new MODELS.Track("Hypnotize", "System of a Down"),
                new MODELS.Track("Tainted Love", "Marilyn Manson"),
                new MODELS.Track("Land of Confusion", "Disturbed"),
                new MODELS.Track("Welcome Home (Sanitarium)", "Metallica"),
                new MODELS.Track("Violent Pornography", "System of a Down"),
                new MODELS.Track("Sonne", "Rammstein"),
                new MODELS.Track("Nemo", "Nightwish"),
                new MODELS.Track("Bodies", "Drowning Pool"),
                new MODELS.Track("Amerika", "Rammstein"),
                new MODELS.Track("Through the Fire and Flames", "DragonForce"),
                new MODELS.Track("Creeping Death", "Metallica"),
                new MODELS.Track("Stricken", "Disturbed"),
                new MODELS.Track("Hallowed Be Thy Name", "Iron Maiden"),
                new MODELS.Track("Engel", "Rammstein"),
                new MODELS.Track("Amaranth", "Nightwish"),
                new MODELS.Track("Hand of Blood", "Bullet For My Valentine"),
                new MODELS.Track("Prison Song", "System of a Down"),
                new MODELS.Track("B.Y.O.B.", "System of a Down"),
                new MODELS.Track("War Pigs", "Black Sabbath"),
                new MODELS.Track("Angel of Death", "Slayer"),
                new MODELS.Track("Sugar", "System of a Down"),
                new MODELS.Track("Ich will", "Rammstein"),
                new MODELS.Track("The Call of Ktulu", "Metallica"),
                new MODELS.Track("The Memory Remains", "Metallica"),
                new MODELS.Track("Question!", "System of a Down"),
                new MODELS.Track("The Day That Never Comes", "Metallica"),
                new MODELS.Track("Cigaro", "System of a Down"),
                new MODELS.Track("Blackened", "Metallica"),
                new MODELS.Track("Links 234", "Rammstein"),
                new MODELS.Track("Got the Life", "KoЯn"),
                new MODELS.Track("The Beautiful People", "Marilyn Manson"),
                new MODELS.Track("Forest", "System of a Down"),
                new MODELS.Track("Revenga", "System of a Down"),
                new MODELS.Track("Breaking the Law", "Judas Priest"),
                new MODELS.Track("Aces High", "Iron Maiden"),
                new MODELS.Track("Cemetery Gates", "Pantera"),
                new MODELS.Track("Until It Sleeps", "Metallica"),
                new MODELS.Track("Vicarious", "Tool"),
                new MODELS.Track("I Stand Alone", "Godsmack"),
                new MODELS.Track("Twisted Transistor", "KoЯn"),
                new MODELS.Track("Crazy Train", "Ozzy Osbourne"),
                new MODELS.Track("Come Clarity", "In Flames"),
                new MODELS.Track("My Plague", "Slipknot"),
                new MODELS.Track("Of Wolf and Man", "Metallica"),
                new MODELS.Track("The Thing That Should Not Be", "Metallica"),
                new MODELS.Track("Bring Me to Life", "Evanescence"),
                new MODELS.Track("Deer Dance", "System of a Down"),
                new MODELS.Track("Psychosocial", "Slipknot"),
                new MODELS.Track("Roots Bloody Roots", "Sepultura"),
                new MODELS.Track("Vermilion", "Slipknot"),
                new MODELS.Track("Take This Life", "In Flames"),
                new MODELS.Track("Coming Undone", "KoЯn"),
                new MODELS.Track("This Is the New Shit", "Marilyn Manson"),
                new MODELS.Track("This Love", "Pantera"),
                new MODELS.Track("Stupify", "Disturbed"),
                new MODELS.Track("Lost in Hollywood", "System of a Down"),
                new MODELS.Track("Sad Statue", "System of a Down"),
                new MODELS.Track("Disposable Heroes", "Metallica"),
                new MODELS.Track("Painkiller", "Judas Priest")
            ]
        }
    }
};