var DATA = {
    playlists: {
        'test': {
            name: 'A playlist I made earlier',
            tracks: [
                new MODELS.Track('Infinity Milk', 'Dananananaykroyd'),
                new MODELS.Track('The Hell Song', 'Sum 41'),
                new MODELS.Track('Dry The Rain', 'The Beta Band'),
                new MODELS.Track('Woozy with Cider', 'James Yorkston'),
                new MODELS.Track('Yoshimi Battles the Pink Robots Pt. 1', 'The Flaming Lips'),
                new MODELS.Track('Stay Loose', 'Belle and Sebastian'),
                new MODELS.Track('Such Great Heights', 'The Postal Service'),
                new MODELS.Track('Stockholm Syndrome', 'Muse'),
                new MODELS.Track('New Slang', 'The Shins'),
                new MODELS.Track('Bluebird', 'Devendra Banhart'),
                new MODELS.Track('Von', 'Sigur Rós'),
                new MODELS.Track('Time Is The Enemy', 'Quantic'),
                new MODELS.Track('Get Ready for Love', 'Nick Cave & The Bad Seeds'),
                new MODELS.Track('Country House', 'Blur'),
                new MODELS.Track('Up In Arms', 'Foo Fighters')
            ]
        },
        'bevan': {
            name: 'Ben and Evan',
            tracks: [
                new MODELS.Track("Rockin' Stroll", "The Lemonheads"),
                new MODELS.Track("Confetti", "The Lemonheads"),
                new MODELS.Track("It's A Shame About Ray", "The Lemonheads"),
                new MODELS.Track("Rudderless", "The Lemonheads"),
                new MODELS.Track("My Drug Buddy", "The Lemonheads"),
                new MODELS.Track("The Turnpike Down", "The Lemonheads"),
                new MODELS.Track("Bit Part", "The Lemonheads"),
                new MODELS.Track("Alison's Starting To Happen", "The Lemonheads"),
                new MODELS.Track("Hannah & Gabi", "The Lemonheads"),
                new MODELS.Track("Kitchen", "The Lemonheads"),
                new MODELS.Track("Ceiling Fan In My Spoon", "The Lemonheads"),
                new MODELS.Track("Frank Mills", "The Lemonheads"),
                new MODELS.Track("Mrs. Robinson", "The Lemonheads"),
                new MODELS.Track("Shaky Ground", "The Lemonheads"),
                new MODELS.Track("It's A Shame About Ray (Demo)", "The Lemonheads"),
                new MODELS.Track("Rockin' Stroll (Demo)", "The Lemonheads"),
                new MODELS.Track("My Drug Buddy (Demo)", "The Lemonheads"),
                new MODELS.Track("Hannah & Gabbi (Demo)", "The Lemonheads"),
                new MODELS.Track("Kitchen (Demo)", "The Lemonheads"),
                new MODELS.Track("Bit Part (Demo)", "The Lemonheads"),
                new MODELS.Track("Rudderless (Demo)", "The Lemonheads"),
                new MODELS.Track("Ceiling Fan In My Spoon (Demo)", "The Lemonheads"),
                new MODELS.Track("Confetti (Demo)", "The Lemonheads"),
                new MODELS.Track("Hiroshima (B B B Benny Hit His Head)", "Ben Folds"),
                new MODELS.Track("Dr. Yang", "Ben Folds"),
                new MODELS.Track("The Frown Song", "Ben Folds"),
                new MODELS.Track("You Don't Know Me (feat. Regina Spektor)", "Ben Folds"),
                new MODELS.Track("Before Cologne", "Ben Folds"),
                new MODELS.Track("Cologne", "Ben Folds"),
                new MODELS.Track("Errant Dog", "Ben Folds"),
                new MODELS.Track("Free Coffee", "Ben Folds"),
                new MODELS.Track("Bitch Went Nuts", "Ben Folds"),
                new MODELS.Track("Brainwascht", "Ben Folds"),
                new MODELS.Track("Effington", "Ben Folds"),
                new MODELS.Track("Kylie From Connecticut", "Ben Folds"),
                new MODELS.Track("Brainwashed", "Ben Folds"),
                new MODELS.Track("Way to Normal", "Ben Folds"),
                new MODELS.Track("Lovesick Diagnostician", "Ben Folds"),
                new MODELS.Track("Free Coffee Town", "Ben Folds"),
                new MODELS.Track("Bitch Went Nutz", "Ben Folds"),
                new MODELS.Track("Frowne Song (Feeble Anthem)", "Ben Folds"),
                new MODELS.Track("Cologne (Piano Orchestra Version)", "Ben Folds"),
                new MODELS.Track("Hiroshima (B B B Benny Hit His Head)", "Ben Folds"),
                new MODELS.Track("You Don't Know Me (feat. Regina Spektor)", "Ben Folds"),
            ]
        },
        'toprock': {
            name: 'Top Tracks tagged with "metal"',
            tracks: [
                new MODELS.Track("Metallica", "Nothing Else Matters"),
                new MODELS.Track("Metallica", "Enter Sandman"),
                new MODELS.Track("Metallica", "Master of Puppets"),
                new MODELS.Track("Metallica", "One"),
                new MODELS.Track("System of a Down", "Toxicity"),
                new MODELS.Track("Metallica", "The Unforgiven"),
                new MODELS.Track("System of a Down", "Chop Suey"),
                new MODELS.Track("Metallica", "Fade to Black"),
                new MODELS.Track("Black Sabbath", "Paranoid"),
                new MODELS.Track("Iron Maiden", "Run to the Hills"),
                new MODELS.Track("Metallica", "Sad but True"),
                new MODELS.Track("Iron Maiden", "The Number of the Beast"),
                new MODELS.Track("Metallica", "Battery"),
                new MODELS.Track("System of a Down", "Lonely Day"),
                new MODELS.Track("Disturbed", "Down With the Sickness"),
                new MODELS.Track("Slipknot", "Before I Forget"),
                new MODELS.Track("System of a Down", "Aerials"),
                new MODELS.Track("Motörhead", "Ace of Spades"),
                new MODELS.Track("Rammstein", "Du hast"),
                new MODELS.Track("Pantera", "Cowboys From Hell"),
                new MODELS.Track("Metallica", "For Whom the Bell Tolls"),
                new MODELS.Track("Metallica", "Whiskey in the Jar"),
                new MODELS.Track("Black Sabbath", "Iron Man"),
                new MODELS.Track("Iron Maiden", "The Trooper"),
                new MODELS.Track("Iron Maiden", "Fear of the Dark"),
                new MODELS.Track("Metallica", "The Unforgiven II"),
                new MODELS.Track("Rob Zombie", "Dragula"),
                new MODELS.Track("Pantera", "Walk"),
                new MODELS.Track("System of a Down", "Chop Suey!"),
                new MODELS.Track("Rage Against the Machine", "Killing in the Name"),
                new MODELS.Track("KoЯn", "Freak on a Leash"),
                new MODELS.Track("Slipknot", "Wait and Bleed"),
                new MODELS.Track("Metallica", "Wherever I May Roam"),
                new MODELS.Track("Bullet For My Valentine", "Tears Don't Fall"),
                new MODELS.Track("Iron Maiden", "2 Minutes to Midnight"),
                new MODELS.Track("Megadeth", "Symphony of Destruction"),
                new MODELS.Track("Slipknot", "Duality"),
                new MODELS.Track("System of a Down", "ATWA"),
                new MODELS.Track("Metallica", "Fuel"),
                new MODELS.Track("Nightwish", "Wish I Had an Angel"),
                new MODELS.Track("Slayer", "Raining Blood"),
                new MODELS.Track("System of a Down", "Hypnotize"),
                new MODELS.Track("Marilyn Manson", "Tainted Love"),
                new MODELS.Track("Disturbed", "Land of Confusion"),
                new MODELS.Track("Metallica", "Welcome Home (Sanitarium)"),
                new MODELS.Track("System of a Down", "Violent Pornography"),
                new MODELS.Track("Rammstein", "Sonne"),
                new MODELS.Track("Nightwish", "Nemo"),
                new MODELS.Track("Drowning Pool", "Bodies"),
                new MODELS.Track("Rammstein", "Amerika"),
                new MODELS.Track("DragonForce", "Through the Fire and Flames"),
                new MODELS.Track("Metallica", "Creeping Death"),
                new MODELS.Track("Disturbed", "Stricken"),
                new MODELS.Track("Iron Maiden", "Hallowed Be Thy Name"),
                new MODELS.Track("Rammstein", "Engel"),
                new MODELS.Track("Nightwish", "Amaranth"),
                new MODELS.Track("Bullet For My Valentine", "Hand of Blood"),
                new MODELS.Track("System of a Down", "Prison Song"),
                new MODELS.Track("System of a Down", "B.Y.O.B."),
                new MODELS.Track("Black Sabbath", "War Pigs"),
                new MODELS.Track("Slayer", "Angel of Death"),
                new MODELS.Track("System of a Down", "Sugar"),
                new MODELS.Track("Rammstein", "Ich will"),
                new MODELS.Track("Metallica", "The Call of Ktulu"),
                new MODELS.Track("Metallica", "The Memory Remains"),
                new MODELS.Track("System of a Down", "Question!"),
                new MODELS.Track("Metallica", "The Day That Never Comes"),
                new MODELS.Track("System of a Down", "Cigaro"),
                new MODELS.Track("Metallica", "Blackened"),
                new MODELS.Track("Rammstein", "Links 234"),
                new MODELS.Track("KoЯn", "Got the Life"),
                new MODELS.Track("Marilyn Manson", "The Beautiful People"),
                new MODELS.Track("System of a Down", "Forest"),
                new MODELS.Track("System of a Down", "Revenga"),
                new MODELS.Track("Judas Priest", "Breaking the Law"),
                new MODELS.Track("Iron Maiden", "Aces High"),
                new MODELS.Track("Pantera", "Cemetery Gates"),
                new MODELS.Track("Metallica", "Until It Sleeps"),
                new MODELS.Track("Tool", "Vicarious"),
                new MODELS.Track("Godsmack", "I Stand Alone"),
                new MODELS.Track("KoЯn", "Twisted Transistor"),
                new MODELS.Track("Ozzy Osbourne", "Crazy Train"),
                new MODELS.Track("In Flames", "Come Clarity"),
                new MODELS.Track("Slipknot", "My Plague"),
                new MODELS.Track("Metallica", "Of Wolf and Man"),
                new MODELS.Track("Metallica", "The Thing That Should Not Be"),
                new MODELS.Track("Evanescence", "Bring Me to Life"),
                new MODELS.Track("System of a Down", "Deer Dance"),
                new MODELS.Track("Slipknot", "Psychosocial"),
                new MODELS.Track("Sepultura", "Roots Bloody Roots"),
                new MODELS.Track("Slipknot", "Vermilion"),
                new MODELS.Track("In Flames", "Take This Life"),
                new MODELS.Track("KoЯn", "Coming Undone"),
                new MODELS.Track("Marilyn Manson", "This Is the New Shit"),
                new MODELS.Track("Pantera", "This Love"),
                new MODELS.Track("Disturbed", "Stupify"),
                new MODELS.Track("System of a Down", "Lost in Hollywood"),
                new MODELS.Track("System of a Down", "Sad Statue"),
                new MODELS.Track("Metallica", "Disposable Heroes"),
                new MODELS.Track("Judas Priest", "Painkiller")
            ]
        }
    }
};