var DATA = {
    playlists: {
        'test': {
            name: 'A playlist I made earlier',
            tracks: [
                new MODELS.Track('Infinity Milk', 'Dananananaykroyd'),
                new MODELS.Track('The Hell Song', 'Sum 41'),
                new MODELS.Track('Dry The Rain', 'The Beta Band'),
                new MODELS.Track('Woozy with Cider', 'James Yorkston'),
                new MODELS.Track('Yoshimi Battles the Pink Robots Pt. 1', 'The Flaming Lips'),
                new MODELS.Track('Stay Loose', 'Belle and Sebastian'),
                new MODELS.Track('Such Great Heights', 'The Postal Service'),
                new MODELS.Track('Stockholm Syndrome', 'Muse'),
                new MODELS.Track('New Slang', 'The Shins'),
                new MODELS.Track('Bluebird', 'Devendra Banhart'),
                new MODELS.Track('Von', 'Sigur Rós'),
                new MODELS.Track('Time Is The Enemy', 'Quantic'),
                new MODELS.Track('Get Ready for Love', 'Nick Cave & The Bad Seeds'),
                new MODELS.Track('Country House', 'Blur'),
                new MODELS.Track('Up In Arms', 'Foo Fighters')
            ]
        },
        'bevan': {
            name: 'Ben and Evan',
            tracks: [
                new MODELS.Track("Rockin' Stroll", "The Lemonheads"),
                new MODELS.Track("Confetti", "The Lemonheads"),
                new MODELS.Track("It's A Shame About Ray", "The Lemonheads"),
                new MODELS.Track("Rudderless", "The Lemonheads"),
                new MODELS.Track("My Drug Buddy", "The Lemonheads"),
                new MODELS.Track("The Turnpike Down", "The Lemonheads"),
                new MODELS.Track("Bit Part", "The Lemonheads"),
                new MODELS.Track("Alison's Starting To Happen", "The Lemonheads"),
                new MODELS.Track("Hannah & Gabi", "The Lemonheads"),
                new MODELS.Track("Kitchen", "The Lemonheads"),
                new MODELS.Track("Ceiling Fan In My Spoon", "The Lemonheads"),
                new MODELS.Track("Frank Mills", "The Lemonheads"),
                new MODELS.Track("Mrs. Robinson", "The Lemonheads"),
                new MODELS.Track("Shaky Ground", "The Lemonheads"),
                new MODELS.Track("It's A Shame About Ray (Demo)", "The Lemonheads"),
                new MODELS.Track("Rockin' Stroll (Demo)", "The Lemonheads"),
                new MODELS.Track("My Drug Buddy (Demo)", "The Lemonheads"),
                new MODELS.Track("Hannah & Gabbi (Demo)", "The Lemonheads"),
                new MODELS.Track("Kitchen (Demo)", "The Lemonheads"),
                new MODELS.Track("Bit Part (Demo)", "The Lemonheads"),
                new MODELS.Track("Rudderless (Demo)", "The Lemonheads"),
                new MODELS.Track("Ceiling Fan In My Spoon (Demo)", "The Lemonheads"),
                new MODELS.Track("Confetti (Demo)", "The Lemonheads"),
                new MODELS.Track("Hiroshima (B B B Benny Hit His Head)", "Ben Folds"),
                new MODELS.Track("Dr. Yang", "Ben Folds"),
                new MODELS.Track("The Frown Song", "Ben Folds"),
                new MODELS.Track("You Don't Know Me (feat. Regina Spektor)", "Ben Folds"),
                new MODELS.Track("Before Cologne", "Ben Folds"),
                new MODELS.Track("Cologne", "Ben Folds"),
                new MODELS.Track("Errant Dog", "Ben Folds"),
                new MODELS.Track("Free Coffee", "Ben Folds"),
                new MODELS.Track("Bitch Went Nuts", "Ben Folds"),
                new MODELS.Track("Brainwascht", "Ben Folds"),
                new MODELS.Track("Effington", "Ben Folds"),
                new MODELS.Track("Kylie From Connecticut", "Ben Folds"),
                new MODELS.Track("Brainwashed", "Ben Folds"),
                new MODELS.Track("Way to Normal", "Ben Folds"),
                new MODELS.Track("Lovesick Diagnostician", "Ben Folds"),
                new MODELS.Track("Free Coffee Town", "Ben Folds"),
                new MODELS.Track("Bitch Went Nutz", "Ben Folds"),
                new MODELS.Track("Frowne Song (Feeble Anthem)", "Ben Folds"),
                new MODELS.Track("Cologne (Piano Orchestra Version)", "Ben Folds"),
                new MODELS.Track("Hiroshima (B B B Benny Hit His Head)", "Ben Folds"),
                new MODELS.Track("You Don't Know Me (feat. Regina Spektor)", "Ben Folds"),
            ]
        }
    }
};
